name: ci_cmake

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_cmake.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: cmake --preset make
    - run: cmake --build build --parallel
    - run: ctest --preset default


  macos:
    env:
      CC: gcc-10
      FC: gfortran-10
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: cmake --preset make
    - run: cmake --build build --parallel
    - run: ctest --preset default


  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - run: cmake --preset makewin
    - run: cmake --build build --parallel
    - run: ctest --preset default
